version: "3.9"

services:
  backend:
    build:
      context: ./RAGProject
    container_name: rag_backend
    ports:
      - "8000:8000"
    env_file:
      - ./RAGProject/.env  # or .env.example if using that
    volumes:
      - ./RAGProject:/app
    depends_on:
      - frontend

  frontend:
    build:
      context: ./frontend
    container_name: rag_frontend
    ports:
      - "3000:80"  # 3000 for local access, 80 inside nginx container
    volumes:
      - ./frontend:/app
